name: deploy-now
on:
  push:
    branches:
      - master

defaults:
  run:
    shell: bash
    working-directory: ./app

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Chackout
        uses: actions/checkout@master
        with:
          # Whether to checkout submodules: `true` to checkout submodules or `recursive` to
          # recursively checkout submodules.
          #
          # When the `ssh-key` input is not provided, SSH URLs beginning with
          # `git@github.com:` are converted to HTTPS.
          #
          # Default: false
          submodules: 'recursive'

      - name: build
        run: docker-compose run --rm app /bin/sh -c "zola build"

      - uses: amondnet/now-deployment@v2
        id: now
        with:
          zeit-token: ${{ secrets.NOW_TOKEN }} # Required
          now-args: "--prod" #Optional
          now-org-id: ${{ secrets.NOW_ORG_ID}} #Required
          now-project-id: ${{ secrets.NOW_PROJECT_ID}} #Required
          working-directory: ./app/public
      - run: |
          echo ${{ steps.now.outputs.preview-url }}
