name: deploy
on:
  push:
    branches:
      - master

defaults:
  run:
    shell: bash
    working-directory: ./app

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Chackout
        uses: actions/checkout@master
      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@master

      - name: build
        run: docker-compose run --rm app /bin/sh -c "zola build"

      - uses: amondnet/now-deployment@v2
        id: now
        with:
          zeit-token: ${{ secrets.NOW_TOKEN }} # Required
          now-args: "--prod" #Optional
          now-org-id: ${{ secrets.NOW_ORG_ID}} #Required
          now-project-id: ${{ secrets.NOW_PROJECT_ID}} #Required
          working-directory: ./public
      - run: |
          echo ${{ steps.now.outputs.preview-url }}
